language: php
php:
  - 7.2.9
sudo: required
dist: trusty

addons:
   chrome: stable

install:
   - cp .env.travis .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - mysql -e 'create database fakultet2018;'
  - composer self-update
  - composer update
  - composer require --dev phpunit/phpunit ^7.0
  #- composer install --no-interaction
  - php artisan migrate
  - php artisan db:seed
  - php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=assets
  - php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=config  
  - php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views  
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  #- vendor/bin/phpunit --debug --bootstrap vendor/autoload.php tests/
  - vendor/bin/phpunit --debug --bootstrap vendor/autoload.php --configuration ./phpunit.xml
  - php artisan dusk